// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type DeleteJobResponse struct {
	DeleteJobID string `json:"deleteJobId"`
}

type JobListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

// ExportDevicesDiscoveredInput represents the input arguments for the query
type ExportDevicesDiscoveredInput struct {
	CompanyID    string `json:"companyID"`
	AssessmentID string `json:"assessmentID"`
}

// DeviceDiscovered represents a single discovered device
type DeviceDiscovered struct {
	ProductIdentifier   string `json:"productIdentifier"`
	Hostname            string `json:"hostname"`
	VendorCd            string `json:"vendorCd"`
	Department          string `json:"department"`
	ReplacementProduct  string `json:"replacementProduct"`
	ContractedStatus    string `json:"contractedStatus"`
	Country             string `json:"country"`
	Locations           string `json:"locations"`
	SerialNumber        string `json:"serialNumber"`
	IPAddress           string `json:"ipAddress"`
	EndOfSale           string `json:"endOfSale"`
	EndOfSupport        string `json:"endOfSupport"`
	ProductFamily       string `json:"productFamily"`
	ProductCategory     string `json:"productCategory"`
	SoftwareType        string `json:"softwareType"`
	SoftwareVersion     string `json:"softwareVersion"`
	ModuleSerialNumber  string `json:"moduleSerialNumber"`
	Type                string `json:"type"`
}

// DevicesDiscoveredResponse represents the response containing discovered devices
type DevicesDiscoveredResponse struct {
	DevicesDiscoveredSuccessfully []*DeviceDiscovered `json:"devicesDiscoveredSuccessfully"`
}