// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type DeleteJobResponse struct {
	DeleteJobID string `json:"deleteJobId"`
}

type DeviceDiscovered struct {
	ProductIdentifier *string `json:"product_identifier,omitempty"`
	Hostname          *string `json:"hostname,omitempty"`
	Vendor            *string `json:"vendor,omitempty"`
	SerialNumber      *string `json:"serial_number,omitempty"`
	IPAddresses       *string `json:"ip_addresses,omitempty"`
}

type DevicesDiscoveredResponse struct {
	DevicesDiscoveredSuccessfully []*DeviceDiscovered `json:"devicesDiscoveredSuccessfully"`
}

type ExportDevicesDiscoveredInput struct {
	CompanyID    string `json:"company_id"`
	AssessmentID string `json:"assessment_id"`
}

type JobListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
}
